### ISSUE TITLE
[FYI] Conda-forge install with existing scipy

### ISSUE THREAD

**Issue by adrn** [dfm/celerite#92]
[This isn't a bug or issue with celerite, just letting you know in case you get bug reports from others!]

In a Python 3.6 conda environment with numpy and scipy already installed, I tried:
```
% conda install -c conda-forge celerite
```
Which seemed to run fine and installed the following, replacing numpy and scipy:
```bash
The following NEW packages will be INSTALLED:

    blas:        1.1-openblas                    conda-forge
    celerite:    0.1.3-np112py36_blas_openblas_0 conda-forge [blas_openblas]
    libgfortran: 3.0.0-0                         conda-forge
    openblas:    0.2.19-1                        conda-forge

The following packages will be UPDATED:

    numpy:       1.12.1-py36_0                               --> 1.12.1-py36_blas_openblas_200      conda-forge [blas_openblas]
    scipy:       0.19.0-np112py36_0                          --> 0.19.0-np112py36_blas_openblas_200 conda-forge [blas_openblas]
```

Replacing numpy forces the scipy update, but the newly installed version of scipy from conda-forge seems broken:
```bash
% python -c "import scipy.optimize"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/adrian/anaconda/envs/comoving-rv/lib/python3.6/site-packages/scipy/optimize/__init__.py", line 232, in <module>
    from .optimize import *
  File "/Users/adrian/anaconda/envs/comoving-rv/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "/Users/adrian/anaconda/envs/comoving-rv/lib/python3.6/site-packages/scipy/optimize/linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: dlopen(/Users/adrian/anaconda/envs/comoving-rv/lib/python3.6/site-packages/scipy/optimize/minpack2.cpython-36m-darwin.so, 2): Library not loaded: /Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libgcc_s.1.dylib
  Referenced from: /Users/adrian/anaconda/envs/comoving-rv/lib/python3.6/site-packages/scipy/optimize/minpack2.cpython-36m-darwin.so
  Reason: image not found
```

It seems like this is fixed just by doing a `conda install scipy` to replace with the default channel scipy.

Thanks for providing a conda install option!

**Comment by dfm** [comment]
Thanks for letting us know! I remember reading an issue about this the other day but I can't seem to track it down. I'll keep this open as a reference until that gets resolved.

**Comment by dfm** [comment]
Did you raise this issue with conda-forge? It doesn't seem to have been updated so it might be good to tell them about it if you're still having this issue...

I'm going to close this for now (haven't heard any other reports and I can't reproduce)

**Comment by adrn** [comment]
Will do!
